import 'package:flutter/material.dart';
import 'package:flutter_medic/models/selectable_item.dart';

enum NewsSourceType { rss, feed }

class NewsSourceItem extends SelectableItem {
  final NewsSourceType type;
  final String url;

  const NewsSourceItem({
    required super.id,
    required super.title,
    required super.subtitle,
    required super.badgeText,
    required super.badgeColor,
    super.logoPath,
    required this.type,
    required this.url,
  });
}

const List<NewsSourceItem> kAllNewsSources = [
  NewsSourceItem(
    id: 'haberturk',
    title: 'Habertürk',
    subtitle: 'Haber & Gündem',
    badgeText: 'HT',
    badgeColor: Color(0xFFE50014),
    logoPath: 'assets/logos/haberturk.png',
    type: NewsSourceType.rss,
    url: 'https://www.haberturk.com/rss',
  ),
  NewsSourceItem(
    id: 'trt',
    title: 'TRT Haber',
    subtitle: 'Türkiye & Gündem',
    badgeText: 'TRT',
    badgeColor: Color(0xFF0F52BA),
    logoPath: 'assets/logos/trt.png',
    type: NewsSourceType.rss,
    url: 'https://www.trthaber.com/manset_articles.rss',
  ),
  NewsSourceItem(
    id: 'ntv',
    title: 'NTV',
    subtitle: 'Türkiye & Dünya',
    badgeText: 'NTV',
    badgeColor: Color(0xFF008751),
    logoPath: 'assets/logos/ntv.jpg',
    type: NewsSourceType.feed,
    url: 'https://www.ntv.com.tr/turkiye.rss',
  ),
  NewsSourceItem(
    id: 'sozcu',
    title: 'Sözcü',
    subtitle: 'Son Dakika & Gazete',
    badgeText: 'SZC',
    badgeColor: Color(0xFFD6181F),
    logoPath: 'assets/logos/sozcu.png',
    type: NewsSourceType.rss,
    url: 'https://www.sozcu.com.tr/rss/tum-haberler.xml',
  ),
  NewsSourceItem(
    id: 'ahaber',
    title: 'A Haber',
    subtitle: 'Gündem & Son Dakika',
    badgeText: 'AH',
    badgeColor: Color(0xFF0A2B66),
    logoPath: 'assets/logos/ahaber.jpeg',
    type: NewsSourceType.rss,
    url: 'https://www.ahaber.com.tr/rss/news.xml',
  ),
  NewsSourceItem(
    id: 'cnnturk',
    title: 'CNN Türk',
    subtitle: 'Türkiye & Dünya',
    badgeText: 'CNN',
    badgeColor: Color(0xFFCC0000),
    logoPath: 'assets/logos/cnnturk.png',
    type: NewsSourceType.rss,
    url: 'https://www.cnnturk.com/feed/rss/turkiye/news',
  ),
  NewsSourceItem(
    id: 'haberglobal',
    title: 'Haber Global',
    subtitle: 'Haber & Canlı',
    badgeText: 'HG',
    badgeColor: Color(0xFF2C3E50),
    logoPath: 'assets/logos/haberglobal.png',
    type: NewsSourceType.rss,
    url: 'https://haberglobal.com.tr/rss',
  ),
  NewsSourceItem(
    id: 'yenisafak',
    title: 'Yeni Şafak',
    subtitle: 'Gündem & Politika',
    badgeText: 'YŞ',
    badgeColor: Color(0xFFC0392B),
    logoPath: 'assets/logos/yenisafak.png',
    type: NewsSourceType.rss,
    url: 'https://www.yenisafak.com/rss',
  ),
  NewsSourceItem(
    id: 'takvim',
    title: 'Takvim',
    subtitle: 'Güncel & Magazin',
    badgeText: 'TKV',
    badgeColor: Color(0xFFE67E22),
    logoPath: 'assets/logos/takvim.png',
    type: NewsSourceType.rss,
    url: 'https://www.takvim.com.tr/rss/news.xml',
  ),
  NewsSourceItem(
    id: 'turkiyegazetesi',
    title: 'Türkiye Gazetesi',
    subtitle: 'Gündem & Ekonomi',
    badgeText: 'TG',
    badgeColor: Color(0xFF16A085),
    logoPath: 'assets/logos/turkiyegazetesi.jpg',
    type: NewsSourceType.rss,
    url: 'https://www.turkiyegazetesi.com.tr/rss',
  ),
  NewsSourceItem(
    id: 'aksamhaberleri',
    title: 'Akşam Haberleri',
    subtitle: 'Gündem & Analiz',
    badgeText: 'AKŞ',
    badgeColor: Color(0xFF8E44AD),
    logoPath: 'assets/logos/aksamhaberleri.png',
    type: NewsSourceType.rss,
    url: 'https://www.aksamhaberleri.com.tr/rss.xml',
  ),
  NewsSourceItem(
    id: 'sabah',
    title: 'Sabah',
    subtitle: 'Son Dakika & Gündem',
    badgeText: 'SBH',
    badgeColor: Color(0xFFD35400),
    logoPath: 'assets/logos/sabah.jpg',
    type: NewsSourceType.rss,
    url: 'https://www.sabah.com.tr/rss/news.xml',
  ),
  NewsSourceItem(
    id: 'sabah_amasya',
    title: 'Sabah - Amasya',
    subtitle: 'Yerel Haber',
    badgeText: 'AMA',
    badgeColor: Color(0xFFD35400),
    type: NewsSourceType.rss,
    url: 'https://www.sabah.com.tr/rss/amasya.xml',
    logoPath: 'assets/logos/sabah.jpg',
  ),
  NewsSourceItem(
    id: 'sabah_bolu',
    title: 'Sabah - Bolu',
    subtitle: 'Yerel Haber',
    badgeText: 'BOL',
    badgeColor: Color(0xFFD35400),
    type: NewsSourceType.rss,
    url: 'https://www.sabah.com.tr/rss/bolu.xml',
    logoPath: 'assets/logos/sabah.jpg',
  ),
  NewsSourceItem(
    id: 'sabah_elazig',
    title: 'Sabah - Elazığ',
    subtitle: 'Yerel Haber',
    badgeText: 'ELA',
    badgeColor: Color(0xFFD35400),
    type: NewsSourceType.rss,
    url: 'https://www.sabah.com.tr/rss/elazig.xml',
    logoPath: 'assets/logos/sabah.jpg',
  ),
  NewsSourceItem(
    id: 'sabah_gaziantep',
    title: 'Sabah - Gaziantep',
    subtitle: 'Yerel Haber',
    badgeText: 'GAZ',
    badgeColor: Color(0xFFD35400),
    type: NewsSourceType.rss,
    url: 'https://www.sabah.com.tr/rss/gaziantep.xml',
    logoPath: 'assets/logos/sabah.jpg',
  ),
  NewsSourceItem(
    id: 'sabah_giresun',
    title: 'Sabah - Giresun',
    subtitle: 'Yerel Haber',
    badgeText: 'GIR',
    badgeColor: Color(0xFFD35400),
    type: NewsSourceType.rss,
    url: 'https://www.sabah.com.tr/rss/giresun.xml',
    logoPath: 'assets/logos/sabah.jpg',
  ),
  NewsSourceItem(
    id: 'sabah_kocaeli',
    title: 'Sabah - Kocaeli',
    subtitle: 'Yerel Haber',
    badgeText: 'KOC',
    badgeColor: Color(0xFFD35400),
    type: NewsSourceType.rss,
    url: 'https://www.kocaelisabah.com/rss',
    logoPath: 'assets/logos/sabah.jpg',
  ),
  NewsSourceItem(
    id: 'sabah_tekirdag',
    title: 'Sabah - Tekirdağ',
    subtitle: 'Yerel Haber',
    badgeText: 'TEK',
    badgeColor: Color(0xFFD35400),
    type: NewsSourceType.rss,
    url: 'https://www.sabah.com.tr/rss/tekirdag.xml',
    logoPath: 'assets/logos/sabah.jpg',
  ),
  NewsSourceItem(
    id: 'sabah_duzce',
    title: 'Sabah - Düzce',
    subtitle: 'Yerel Haber',
    badgeText: 'DÜZ',
    badgeColor: Color(0xFFD35400),
    type: NewsSourceType.rss,
    url: 'https://www.duzcesonhaber.com/rss-servisi',
    logoPath: 'assets/logos/sabah.jpg',
  ),
  NewsSourceItem(
    id: 'i̇lkhaber',
    title: 'İlkhaber',
    subtitle: 'Adana',
    badgeText: '01',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.ilkhaber-gazetesi.com/rss',
    logoPath: 'assets/logos/01_İlkhaber_logo.png',
  ),
  NewsSourceItem(
    id: '5_ocak_gazetesi',
    title: '5 Ocak Gazetesi',
    subtitle: 'Adana',
    badgeText: '01',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.5ocakgazetesi.com/rss/sondakika',
    logoPath: 'assets/logos/01_5_Ocak_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'yeniyol_gazetesi',
    title: 'Yeniyol Gazetesi',
    subtitle: 'Adıyaman',
    badgeText: '02',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.yeniyolgazetesi.com/rss/news',
    logoPath: 'assets/logos/02_Yeniyol_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'afyon_haber',
    title: 'Afyon Haber',
    subtitle: 'Afyonkarahisar',
    badgeText: '03',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.afyonhaber.com/rss/son-dakika',
    logoPath: 'assets/logos/03_Afyon_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'odak_gazetesi',
    title: 'Odak Gazetesi',
    subtitle: 'Afyonkarahisar',
    badgeText: '03',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.odakgazetesi.com/rss/sondakika',
    logoPath: 'assets/logos/03_Odak_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'agri_memleket',
    title: 'Ağrı Memleket',
    subtitle: 'Ağrı',
    badgeText: '04',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.agrimemleket.com/rss/sondakika',
    logoPath: 'assets/logos/04_Ağrı_Memleket_logo.png',
  ),
  NewsSourceItem(
    id: 'narinkale_gazetesi',
    title: 'Narinkale Gazetesi',
    subtitle: 'Ağrı',
    badgeText: '04',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://narinkalegazetesi.net/rss.xml',
    logoPath: null,
  ),
  NewsSourceItem(
    id: 'sonsoz',
    title: 'Sonsöz',
    subtitle: 'Ankara',
    badgeText: '06',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://sonsoz.com.tr/rss/sondakika',
    logoPath: 'assets/logos/06_Sonsöz_logo.png',
  ),
  NewsSourceItem(
    id: 'baskent_gazetesi',
    title: 'Başkent Gazetesi',
    subtitle: 'Ankara',
    badgeText: '06',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.baskentgazete.com.tr/rss/sondakika',
    logoPath: 'assets/logos/06_Başkent_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'akdeniz_gercek',
    title: 'Akdeniz Gerçek',
    subtitle: 'Antalya',
    badgeText: '07',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.akdenizgercek.com.tr/rss/news',
    logoPath: 'assets/logos/07_Akdeniz_Gerçek_logo.png',
  ),
  NewsSourceItem(
    id: 'antalya_ekspres',
    title: 'Antalya Ekspres',
    subtitle: 'Antalya',
    badgeText: '07',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.antalyaekspres.com.tr/rss/son-dakika',
    logoPath: 'assets/logos/07_Antalya_Ekspres_logo.png',
  ),
  NewsSourceItem(
    id: 'antalya_korfez',
    title: 'Antalya Körfez',
    subtitle: 'Antalya',
    badgeText: '07',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.antalyakorfez.com/rss/son-dakika',
    logoPath: 'assets/logos/07_Antalya_Körfez_logo.png',
  ),
  NewsSourceItem(
    id: 'gundem_artvin',
    title: 'Gündem Artvin',
    subtitle: 'Artvin',
    badgeText: '08',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.gundemartvin.com/rss/sondakika',
    logoPath: 'assets/logos/08_Gündem_Artvin_logo.png',
  ),
  NewsSourceItem(
    id: '7_mart_gazetesi',
    title: '7 Mart Gazetesi',
    subtitle: 'Artvin',
    badgeText: '08',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.7martgazetesi.net/rss',
    logoPath: 'assets/logos/08_7_Mart_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'ses_gazetesi',
    title: 'Ses Gazetesi',
    subtitle: 'Aydın',
    badgeText: '09',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.sesgazetesi.com.tr/rss/sondakika',
    logoPath: 'assets/logos/09_Ses_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'hedef_gazetesi',
    title: 'Hedef Gazetesi',
    subtitle: 'Aydın',
    badgeText: '09',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.aydinhedef.com.tr/rss',
    logoPath: 'assets/logos/09_Hedef_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'aydin_denge',
    title: 'Aydın Denge',
    subtitle: 'Aydın',
    badgeText: '09',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.aydindenge.com.tr/feeds/rss',
    logoPath: 'assets/logos/09_Aydın_Denge_logo.png',
  ),
  NewsSourceItem(
    id: 'balikesir_birlik',
    title: 'Balıkesir Birlik',
    subtitle: 'Balıkesir',
    badgeText: '10',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://balikesirbirlikgazetesi.com/feed',
    logoPath: 'assets/logos/10_Balıkesir_Birlik_logo.png',
  ),
  NewsSourceItem(
    id: 'balikesir_politika',
    title: 'Balıkesir Politika',
    subtitle: 'Balıkesir',
    badgeText: '10',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.politikam.com/rss/son-dakika',
    logoPath: 'assets/logos/10_Balıkesir_Politika_logo.png',
  ),
  NewsSourceItem(
    id: 'bilecik_haber',
    title: 'Bilecik Haber',
    subtitle: 'Bilecik',
    badgeText: '11',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.bilecikhaber.com.tr/service/rss.php',
    logoPath: 'assets/logos/11_Bilecik_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'yarin_gazetesi',
    title: 'Yarın Gazetesi',
    subtitle: 'Bilecik',
    badgeText: '11',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.yarin11.com/rss/sondakika',
    logoPath: 'assets/logos/11_Yarın_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'bilecik11',
    title: 'Bilecik11',
    subtitle: 'Bilecik',
    badgeText: '11',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://bilecik11.com/feed/',
    logoPath: 'assets/logos/11_Bilecik11_logo.png',
  ),
  NewsSourceItem(
    id: 'bingol_kent_haber',
    title: 'Bingöl Kent Haber',
    subtitle: 'Bingöl',
    badgeText: '12',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.bingolkenthaber.com/rss/son-dakika',
    logoPath: 'assets/logos/12_Bingöl_Kent_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'bingol_online',
    title: 'Bingöl Online',
    subtitle: 'Bingöl',
    badgeText: '12',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.bingolonline.com/rss',
    logoPath: 'assets/logos/12_Bingöl_Online_logo.png',
  ),
  NewsSourceItem(
    id: 'bingol_surmanset',
    title: 'Bingöl Sürmanşet',
    subtitle: 'Bingöl',
    badgeText: '12',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.bingolsurmanset.com/rss/son-dakika',
    logoPath: 'assets/logos/12_Bingöl_Sürmanşet_logo.png',
  ),
  NewsSourceItem(
    id: 'bitlis_haber_13',
    title: 'Bitlis Haber 13',
    subtitle: 'Bitlis',
    badgeText: '13',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.bitlishaber13.net/rss/son-dakika',
    logoPath: 'assets/logos/13_Bitlis_Haber_13_logo.png',
  ),
  NewsSourceItem(
    id: 'bitlis_dogru_haber',
    title: 'Bitlis Doğru Haber',
    subtitle: 'Bitlis',
    badgeText: '13',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://bitlisdogruhaber.com/rss',
    logoPath: 'assets/logos/13_Bitlis_Doğru_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'tatvan_sesi',
    title: 'Tatvan Sesi',
    subtitle: 'Bitlis',
    badgeText: '13',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://tatvansesi.com.tr/rss.xml',
    logoPath: 'assets/logos/13_Tatvan_Sesi_logo.png',
  ),
  NewsSourceItem(
    id: 'burdur_yenigun',
    title: 'Burdur Yenigün',
    subtitle: 'Burdur',
    badgeText: '15',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.burduryenigun.com/rss/sondakika',
    logoPath: 'assets/logos/15_Burdur_Yenigün_logo.png',
  ),
  NewsSourceItem(
    id: 'cagdas_burdur',
    title: 'Çağdaş Burdur',
    subtitle: 'Burdur',
    badgeText: '15',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.cagdasburdur.com/rss.xml',
    logoPath: 'assets/logos/15_Çağdaş_Burdur_logo.png',
  ),
  NewsSourceItem(
    id: 'olay_gazetesi',
    title: 'Olay Gazetesi',
    subtitle: 'Bursa',
    badgeText: '16',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.olay.com.tr/rss/son-dakika',
    logoPath: 'assets/logos/16_Olay_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'bursa_hakimiyet',
    title: 'Bursa Hakimiyet',
    subtitle: 'Bursa',
    badgeText: '16',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.bursahakimiyet.com.tr/rss',
    logoPath: 'assets/logos/16_Bursa_Hakimiyet_logo.png',
  ),
  NewsSourceItem(
    id: 'bursa_haber',
    title: 'Bursa Haber',
    subtitle: 'Bursa',
    badgeText: '16',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.bursahaber.com/rss',
    logoPath: 'assets/logos/16_Bursa_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'canakkale_olay',
    title: 'Çanakkale Olay',
    subtitle: 'Çanakkale',
    badgeText: '17',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.canakkaleolay.com/rss',
    logoPath: 'assets/logos/17_Çanakkale_Olay_logo.png',
  ),
  NewsSourceItem(
    id: 'bogaz_gazetesi',
    title: 'Boğaz Gazetesi',
    subtitle: 'Çanakkale',
    badgeText: '17',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.bogazgazetesi.com.tr/rss/sondakika',
    logoPath: 'assets/logos/17_Boğaz_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'kalenin_sesi',
    title: 'Kalenin Sesi',
    subtitle: 'Çanakkale',
    badgeText: '17',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.kaleninsesi.com/rss',
    logoPath: 'assets/logos/17_Kalenin_Sesi_logo.png',
  ),
  NewsSourceItem(
    id: 'cankiri_gazete',
    title: 'Çankırı Gazete',
    subtitle: 'Çankırı',
    badgeText: '18',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.cankirigazete.com/feed/',
    logoPath: 'assets/logos/18_Çankırı_Gazete_logo.png',
  ),
  NewsSourceItem(
    id: 'karatekin_gazetesi',
    title: 'Karatekin Gazetesi',
    subtitle: 'Çankırı',
    badgeText: '18',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.karatekin.com.tr/?feed=rss2',
    logoPath: 'assets/logos/18_Karatekin_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'corum_haber',
    title: 'Çorum Haber',
    subtitle: 'Çorum',
    badgeText: '19',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.corumhaber.net/rss/son-dakika',
    logoPath: 'assets/logos/19_Çorum_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'corum_hakimiyet',
    title: 'Çorum Hakimiyet',
    subtitle: 'Çorum',
    badgeText: '19',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.corumhakimiyet.net/rss/son-dakika',
    logoPath: null,
  ),
  NewsSourceItem(
    id: 'kesin_karar',
    title: 'Kesin Karar',
    subtitle: 'Çorum',
    badgeText: '19',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.kesinkarar.com/rss/news',
    logoPath: 'assets/logos/19_Kesin_Karar_logo.png',
  ),
  NewsSourceItem(
    id: 'denizli_gazetesi',
    title: 'Denizli Gazetesi',
    subtitle: 'Denizli',
    badgeText: '20',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.denizligazetesi.com/rss/son-dakika',
    logoPath: 'assets/logos/20_Denizli_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'denizli_haber',
    title: 'Denizli Haber',
    subtitle: 'Denizli',
    badgeText: '20',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.denizlihaber.com/feed/',
    logoPath: 'assets/logos/20_Denizli_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'guneydogu_ekspres',
    title: 'Güneydoğu Ekspres',
    subtitle: 'Diyarbakır',
    badgeText: '21',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.guneydoguekspres.com/rss/son-dakika',
    logoPath: 'assets/logos/21_Güneydoğu_Ekspres_logo.png',
  ),
  NewsSourceItem(
    id: 'diyarbakir_yenigun',
    title: 'Diyarbakır Yenigün',
    subtitle: 'Diyarbakır',
    badgeText: '21',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://diyarbakiryenigun.com/service/rss.php',
    logoPath: 'assets/logos/21_Diyarbakır_Yenigün_logo.png',
  ),
  NewsSourceItem(
    id: 'diyarbakir_soz',
    title: 'Diyarbakır Söz',
    subtitle: 'Diyarbakır',
    badgeText: '21',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://diyarbakirsoz.com/rss/rss',
    logoPath: 'assets/logos/21_Diyarbakır_Söz_logo.png',
  ),
  NewsSourceItem(
    id: 'hudut_gazetesi',
    title: 'Hudut Gazetesi',
    subtitle: 'Edirne',
    badgeText: '22',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://hudutgazetesi.com/rss',
    logoPath: 'assets/logos/22_Hudut_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'vatandas_gazetesi',
    title: 'Vatandaş Gazetesi',
    subtitle: 'Edirne',
    badgeText: '22',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.vatandasgazetesi.com.tr/rss/son-dakika',
    logoPath: null,
  ),
  NewsSourceItem(
    id: 'edirne_gazetesi',
    title: 'Edirne Gazetesi',
    subtitle: 'Edirne',
    badgeText: '22',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.edirnegazetesi.com.tr/rss_son-dakika-_13.xml',
    logoPath: 'assets/logos/22_Edirne_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'gundem24',
    title: 'Gündem24',
    subtitle: 'Erzincan',
    badgeText: '24',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://gundem24.com.tr/rss',
    logoPath: 'assets/logos/24_Gündem24_logo.png',
  ),
  NewsSourceItem(
    id: 'erzincan_net',
    title: 'Erzincan Net',
    subtitle: 'Erzincan',
    badgeText: '24',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.erzincannet.com/rss/sondakika',
    logoPath: 'assets/logos/24_Erzincan_Net_logo.png',
  ),
  NewsSourceItem(
    id: 'dogu_gazetesi',
    title: 'Doğu Gazetesi',
    subtitle: 'Erzincan',
    badgeText: '24',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.dogugazetesi.com/rss/son-dakika',
    logoPath: 'assets/logos/24_Doğu_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'pusula_gazetesi',
    title: 'Pusula Gazetesi',
    subtitle: 'Erzurum',
    badgeText: '25',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.gazetepusula.net/rss.xml',
    logoPath: 'assets/logos/25_Pusula_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'erzurum_gunebakis',
    title: 'Erzurum Günebakış',
    subtitle: 'Erzurum',
    badgeText: '25',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://erzurumgunebakis.com/rss.xml',
    logoPath: 'assets/logos/25_Erzurum_Günebakış_logo.png',
  ),
  NewsSourceItem(
    id: '2_eylul',
    title: '2 Eylül',
    subtitle: 'Eskişehir',
    badgeText: '26',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.2eylul.com.tr/rss/son-dakika',
    logoPath: 'assets/logos/26_2_Eylül_logo.png',
  ),
  NewsSourceItem(
    id: 'anadolu_gazetesi',
    title: 'Anadolu Gazetesi',
    subtitle: 'Eskişehir',
    badgeText: '26',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.anadolugazetesi.com/RSS.xml',
    logoPath: 'assets/logos/26_Anadolu_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'gumushane.gen.tr',
    title: 'Gümüşhane.gen.tr',
    subtitle: 'Gümüşhane',
    badgeText: '29',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.gumushane.gen.tr/rss/news',
    logoPath: 'assets/logos/29_Gümüşhane.gen.tr_logo.png',
  ),
  NewsSourceItem(
    id: 'hakkâri_i̇l_sesi',
    title: 'Hakkâri İl Sesi',
    subtitle: 'Hakkâri',
    badgeText: '30',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.hakkariilsesigazetesi.com/rss/sondakika',
    logoPath: 'assets/logos/30_Hakkâri_İl_Sesi_logo.png',
  ),
  NewsSourceItem(
    id: 'hakkari_objektif_haber',
    title: 'Hakkari Objektif Haber',
    subtitle: 'Hakkâri',
    badgeText: '30',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.hakkariobjektifhaber.com/service/rss.php',
    logoPath: 'assets/logos/30_Hakkari_Objektif_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'yuksekova_haber',
    title: 'Yüksekova Haber',
    subtitle: 'Hakkâri',
    badgeText: '30',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.yuksekovahaber.com.tr/service/rss.php',
    logoPath: 'assets/logos/30_Yüksekova_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'hatay_soz',
    title: 'Hatay Söz',
    subtitle: 'Hatay',
    badgeText: '31',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.hataysoz.com/rss.php',
    logoPath: 'assets/logos/31_Hatay_Söz_logo.png',
  ),
  NewsSourceItem(
    id: 'antakya_gazetesi',
    title: 'Antakya Gazetesi',
    subtitle: 'Hatay',
    badgeText: '31',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://antakyagazetesi.com/feed/',
    logoPath: 'assets/logos/31_Antakya_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'asi_gazetesi',
    title: 'Asi Gazetesi',
    subtitle: 'Hatay',
    badgeText: '31',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.asigazetesi.com/rss/son-dakika',
    logoPath: 'assets/logos/31_Asi_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'bomba_32',
    title: 'Bomba 32',
    subtitle: 'Isparta',
    badgeText: '32',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.bomba32.com/rss/sondakika',
    logoPath: 'assets/logos/32_Bomba_32_logo.png',
  ),
  NewsSourceItem(
    id: 'demokrat_gazetesi',
    title: 'Demokrat Gazetesi',
    subtitle: 'Isparta',
    badgeText: '32',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.demokrat32.com/rss/sondakika',
    logoPath: 'assets/logos/32_Demokrat_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'haber32',
    title: 'Haber32',
    subtitle: 'Isparta',
    badgeText: '32',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.haber32.com.tr/rss/son-dakika',
    logoPath: 'assets/logos/32_Haber32_logo.png',
  ),
  NewsSourceItem(
    id: 'cukurova_gazetesi',
    title: 'Çukurova Gazetesi',
    subtitle: 'Mersin',
    badgeText: '33',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://cukurovagazetesi.com/rss/sondakika',
    logoPath: 'assets/logos/33_Çukurova_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'i̇stanbul_gazetesi',
    title: 'İstanbul Gazetesi',
    subtitle: 'İstanbul',
    badgeText: '34',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.istanbulgazetesi.com.tr/rss/sondakika',
    logoPath: 'assets/logos/34_İstanbul_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'kadikoy_life',
    title: 'Kadıköy Life',
    subtitle: 'İstanbul',
    badgeText: '34',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.kadikoylife.com/feed/',
    logoPath: 'assets/logos/34_Kadıköy_Life_logo.png',
  ),
  NewsSourceItem(
    id: 'yeni_bakis',
    title: 'Yeni Bakış',
    subtitle: 'İzmir',
    badgeText: '35',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.yenibakis.com.tr/rss/sondakika',
    logoPath: 'assets/logos/35_Yeni_Bakış_logo.png',
  ),
  NewsSourceItem(
    id: 'dokuz_eylul',
    title: 'Dokuz Eylül',
    subtitle: 'İzmir',
    badgeText: '35',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.dokuzeylul.com/rss/sondakika',
    logoPath: 'assets/logos/35_Dokuz_Eylül_logo.png',
  ),
  NewsSourceItem(
    id: 'ege_telgraf',
    title: 'Ege Telgraf',
    subtitle: 'İzmir',
    badgeText: '35',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.egetelgraf.com/rss/sondakika',
    logoPath: 'assets/logos/35_Ege_Telgraf_logo.png',
  ),
  NewsSourceItem(
    id: 'kars_hakimiyet',
    title: 'Kars Hakimiyet',
    subtitle: 'Kars',
    badgeText: '36',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.karshakimiyet.com/service/rss.php',
    logoPath: 'assets/logos/36_Kars_Hakimiyet_logo.png',
  ),
  NewsSourceItem(
    id: 'kars_manset',
    title: 'Kars Manşet',
    subtitle: 'Kars',
    badgeText: '36',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.karsmanset.com/service/rss.php',
    logoPath: 'assets/logos/36_Kars_Manşet_logo.png',
  ),
  NewsSourceItem(
    id: 'kars_pusula',
    title: 'Kars Pusula',
    subtitle: 'Kars',
    badgeText: '36',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://karspusula.com/rss.xml',
    logoPath: 'assets/logos/36_Kars_Pusula_logo.png',
  ),
  NewsSourceItem(
    id: 'kastamonu_i̇stiklal',
    title: 'Kastamonu İstiklal',
    subtitle: 'Kastamonu',
    badgeText: '37',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.kastamonuistiklal.com/rss/son-dakika',
    logoPath: 'assets/logos/37_Kastamonu_İstiklal_logo.png',
  ),
  NewsSourceItem(
    id: 'kastamonu_gundem',
    title: 'Kastamonu Gündem',
    subtitle: 'Kastamonu',
    badgeText: '37',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.kastamonugundemgazetesi.com/rss/sondakika',
    logoPath: 'assets/logos/37_Kastamonu_Gündem_logo.png',
  ),
  NewsSourceItem(
    id: 'deniz_postasi',
    title: 'Deniz Postası',
    subtitle: 'Kayseri',
    badgeText: '38',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.denizpostasi.com/rss/sondakika',
    logoPath: 'assets/logos/38_Deniz_Postası_logo.png',
  ),
  NewsSourceItem(
    id: 'gorunum_gazetesi',
    title: 'Görünüm Gazetesi',
    subtitle: 'Kırklareli',
    badgeText: '39',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.gorunumgazetesi.com.tr/blog-feed.xml',
    logoPath: 'assets/logos/39_Görünüm_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'yesilyurt_gazetesi',
    title: 'Yeşilyurt Gazetesi',
    subtitle: 'Kırklareli',
    badgeText: '39',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.yesilyurtgazete.com/rss',
    logoPath: 'assets/logos/39_Yeşilyurt_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'onadim_gazetesi',
    title: 'Önadım Gazetesi',
    subtitle: 'Kırklareli',
    badgeText: '39',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.onadimgazetesi.com/rss.xml',
    logoPath: 'assets/logos/39_Önadım_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'kirsehir_cigdem',
    title: 'Kırşehir Çiğdem',
    subtitle: 'Kırşehir',
    badgeText: '40',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.kirsehircigdem.com/rss/son-dakika',
    logoPath: 'assets/logos/40_Kırşehir_Çiğdem_logo.png',
  ),
  NewsSourceItem(
    id: 'kirsehir_memleket',
    title: 'Kırşehir Memleket',
    subtitle: 'Kırşehir',
    badgeText: '40',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.kirsehirmemleket.com.tr/rss',
    logoPath: 'assets/logos/40_Kırşehir_Memleket_logo.png',
  ),
  NewsSourceItem(
    id: 'kirsehir_arena',
    title: 'Kırşehir Arena',
    subtitle: 'Kırşehir',
    badgeText: '40',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.kirsehirarenagazetesi.com/feed/',
    logoPath: 'assets/logos/40_Kırşehir_Arena_logo.png',
  ),
  NewsSourceItem(
    id: 'konya_yenigun',
    title: 'Konya Yenigün',
    subtitle: 'Konya',
    badgeText: '42',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.konyayenigun.com/rss/son-dakika',
    logoPath: 'assets/logos/42_Konya_Yenigün_logo.png',
  ),
  NewsSourceItem(
    id: 'kutahya_ekspres',
    title: 'Kütahya Ekspres',
    subtitle: 'Kütahya',
    badgeText: '43',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://kutahyaekspres.com/rss/sondakika',
    logoPath: 'assets/logos/43_Kütahya_Ekspres_logo.png',
  ),
  NewsSourceItem(
    id: 'kutahya_postasi',
    title: 'Kütahya Postası',
    subtitle: 'Kütahya',
    badgeText: '43',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.kutahyapostasigazetesi.com.tr/feed/',
    logoPath: 'assets/logos/43_Kütahya_Postası_logo.png',
  ),
  NewsSourceItem(
    id: 'malatya_haber',
    title: 'Malatya Haber',
    subtitle: 'Malatya',
    badgeText: '44',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://malatyahaber.com/rss/son-dakika',
    logoPath: 'assets/logos/44_Malatya_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'bu_sabah_malatya',
    title: 'Bu Sabah Malatya',
    subtitle: 'Malatya',
    badgeText: '44',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.busabahmalatya.com/rss/sondakika',
    logoPath: 'assets/logos/44_Bu_Sabah_Malatya_logo.png',
  ),
  NewsSourceItem(
    id: 'manisa_kulis',
    title: 'Manisa Kulis',
    subtitle: 'Manisa',
    badgeText: '45',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.manisakulishaber.com/rss/son-dakika',
    logoPath: 'assets/logos/45_Manisa_Kulis_logo.png',
  ),
  NewsSourceItem(
    id: 'manisa’da_gundem',
    title: 'Manisa’da Gündem',
    subtitle: 'Manisa',
    badgeText: '45',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.manisadagundem.com/rss/sondakika',
    logoPath: 'assets/logos/45_Manisa’da_Gündem_logo.png',
  ),
  NewsSourceItem(
    id: 'kahramanmaras_manset',
    title: 'Kahramanmaraş Manşet',
    subtitle: 'Kahramanmaraş',
    badgeText: '46',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.marasmanset.com/rss/sondakika',
    logoPath: 'assets/logos/46_Kahramanmaraş_Manşet_logo.png',
  ),
  NewsSourceItem(
    id: 'maras_gundem',
    title: 'Maraş Gündem',
    subtitle: 'Kahramanmaraş',
    badgeText: '46',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.marasgundem.com.tr/service/rss.php',
    logoPath: 'assets/logos/46_Maraş_Gündem_logo.png',
  ),
  NewsSourceItem(
    id: 'maras_yenigun',
    title: 'Maraş Yenigün',
    subtitle: 'Kahramanmaraş',
    badgeText: '46',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.marasyenigun.com/rss.xml',
    logoPath: 'assets/logos/46_Maraş_Yenigün_logo.png',
  ),
  NewsSourceItem(
    id: 'mardin_i̇letisim',
    title: 'Mardin İletişim',
    subtitle: 'Mardin',
    badgeText: '47',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.mardiniletisimgazetesi.com.tr/feed/',
    logoPath: 'assets/logos/47_Mardin_İletişim_logo.png',
  ),
  NewsSourceItem(
    id: 'hamle_gazetesi',
    title: 'Hamle Gazetesi',
    subtitle: 'Muğla',
    badgeText: '48',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.hamlegazetesi.com.tr/rss/sondakika',
    logoPath: 'assets/logos/48_Hamle_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'haber49',
    title: 'Haber49',
    subtitle: 'Muş',
    badgeText: '49',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://haber49.net/rss/son-dakika',
    logoPath: 'assets/logos/49_Haber49_logo.png',
  ),
  NewsSourceItem(
    id: 'muskara_haber',
    title: 'Muşkara Haber',
    subtitle: 'Nevşehir',
    badgeText: '50',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.muskarahaber.com/rss/son-dakika',
    logoPath: 'assets/logos/50_Muşkara_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'fi̇b_haber',
    title: 'FİB Haber',
    subtitle: 'Nevşehir',
    badgeText: '50',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.fibhaber.com/rss/sondakika',
    logoPath: 'assets/logos/50_FİB_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'nigde_anadolu_haber',
    title: 'Niğde Anadolu Haber',
    subtitle: 'Niğde',
    badgeText: '51',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://nigdeanadoluhaber.com.tr/rss/sondakika',
    logoPath: 'assets/logos/51_Niğde_Anadolu_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'nigde_gunaydin',
    title: 'Niğde Günaydın',
    subtitle: 'Niğde',
    badgeText: '51',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://nigdegunaydin.com/rss.xml',
    logoPath: 'assets/logos/51_Niğde_Günaydın_logo.png',
  ),
  NewsSourceItem(
    id: 'ordu_gazete',
    title: 'Ordu Gazete',
    subtitle: 'Ordu',
    badgeText: '52',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.ordugazete.com/rss',
    logoPath: 'assets/logos/52_Ordu_Gazete_logo.png',
  ),
  NewsSourceItem(
    id: 'rizedeyiz',
    title: 'Rizedeyiz',
    subtitle: 'Rize',
    badgeText: '53',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.rizedeyiz.com/rss/sondakika',
    logoPath: 'assets/logos/53_Rizedeyiz_logo.png',
  ),
  NewsSourceItem(
    id: 'rize’nin_sesi',
    title: 'Rize’nin Sesi',
    subtitle: 'Rize',
    badgeText: '53',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.rizeninsesi.net/rss',
    logoPath: 'assets/logos/53_Rize’nin_Sesi_logo.png',
  ),
  NewsSourceItem(
    id: 'olay53',
    title: 'Olay53',
    subtitle: 'Rize',
    badgeText: '53',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.olay53.com/service/rss.php',
    logoPath: 'assets/logos/53_Olay53_logo.png',
  ),
  NewsSourceItem(
    id: 'yeni_sakarya',
    title: 'Yeni Sakarya',
    subtitle: 'Sakarya',
    badgeText: '54',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.yenisakarya.com/rss/sondakika',
    logoPath: 'assets/logos/54_Yeni_Sakarya_logo.png',
  ),
  NewsSourceItem(
    id: 'gazete_gercek',
    title: 'Gazete Gerçek',
    subtitle: 'Samsun',
    badgeText: '55',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.gazetegercek.com.tr/rss',
    logoPath: 'assets/logos/55_Gazete_Gerçek_logo.png',
  ),
  NewsSourceItem(
    id: 'samsun_gazetesi',
    title: 'Samsun Gazetesi',
    subtitle: 'Samsun',
    badgeText: '55',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.samsungazetesi.com/rss/son-dakika',
    logoPath: 'assets/logos/55_Samsun_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'mucadele_gazetesi',
    title: 'Mücadele Gazetesi',
    subtitle: 'Siirt',
    badgeText: '56',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.mucadelegazetesi.com.tr/rss/sondakika',
    logoPath: null,
  ),
  NewsSourceItem(
    id: 'siirtpress',
    title: 'SiirtPress',
    subtitle: 'Siirt',
    badgeText: '56',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.siirtpress.com/feed',
    logoPath: 'assets/logos/56_SiirtPress_logo.png',
  ),
  NewsSourceItem(
    id: 'vitrin_haber',
    title: 'Vitrin Haber',
    subtitle: 'Sinop',
    badgeText: '57',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.vitrinhaber.com/rss',
    logoPath: 'assets/logos/57_Vitrin_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'haber57',
    title: 'Haber57',
    subtitle: 'Sinop',
    badgeText: '57',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.haber57.com.tr/rss/son-dakika',
    logoPath: 'assets/logos/57_Haber57_logo.png',
  ),
  NewsSourceItem(
    id: 'ajans_sinop',
    title: 'Ajans Sinop',
    subtitle: 'Sinop',
    badgeText: '57',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.ajanssinop.com/rss',
    logoPath: 'assets/logos/57_Ajans_Sinop_logo.png',
  ),
  NewsSourceItem(
    id: 'sivas_ekspres',
    title: 'Sivas Ekspres',
    subtitle: 'Sivas',
    badgeText: '58',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.sivasekspres.com/service/rss.php',
    logoPath: 'assets/logos/58_Sivas_Ekspres_logo.png',
  ),
  NewsSourceItem(
    id: 'hursoz_gazetesi',
    title: 'Hürsöz Gazetesi',
    subtitle: 'Tokat',
    badgeText: '60',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.hursozgazetesi.com/rss/sondakika',
    logoPath: 'assets/logos/60_Hürsöz_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'tokat_haber',
    title: 'Tokat Haber',
    subtitle: 'Tokat',
    badgeText: '60',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.tokathaber.com.tr/rss/son-dakika',
    logoPath: 'assets/logos/60_Tokat_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'tokat_haber_60',
    title: 'Tokat Haber 60',
    subtitle: 'Tokat',
    badgeText: '60',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://tokathaber60.com/feed/',
    logoPath: 'assets/logos/60_Tokat_Haber_60_logo.png',
  ),
  NewsSourceItem(
    id: 'taka_gazetesi',
    title: 'Taka Gazetesi',
    subtitle: 'Trabzon',
    badgeText: '61',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.takagazete.com.tr/rss/sondakika',
    logoPath: 'assets/logos/61_Taka_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'dersim_ekspres',
    title: 'Dersim Ekspres',
    subtitle: 'Tunceli',
    badgeText: '62',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.dersimekspres.com/rss.xml',
    logoPath: 'assets/logos/62_Dersim_Ekspres_logo.png',
  ),
  NewsSourceItem(
    id: 'urfanatik',
    title: 'Urfanatik',
    subtitle: 'Şanlıurfa',
    badgeText: '63',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.urfanatik.com/rss/son-dakika',
    logoPath: 'assets/logos/63_Urfanatik_logo.png',
  ),
  NewsSourceItem(
    id: 'gazete_i̇pekyol',
    title: 'Gazete İpekyol',
    subtitle: 'Şanlıurfa',
    badgeText: '63',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.gazeteipekyol.com/rss',
    logoPath: 'assets/logos/63_Gazete_İpekyol_logo.png',
  ),
  NewsSourceItem(
    id: 'usak_olay',
    title: 'Uşak Olay',
    subtitle: 'Uşak',
    badgeText: '64',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.usakolay.com/service/rss.php',
    logoPath: 'assets/logos/64_Uşak_Olay_logo.png',
  ),
  NewsSourceItem(
    id: 'usak_haber_gazetesi',
    title: 'Uşak Haber Gazetesi',
    subtitle: 'Uşak',
    badgeText: '64',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://usakhabergazetesi.com.tr/rss/son-dakika',
    logoPath: 'assets/logos/64_Uşak_Haber_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'van_olay',
    title: 'Van Olay',
    subtitle: 'Van',
    badgeText: '65',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.vanolay.com/rss/son-dakika',
    logoPath: 'assets/logos/65_Van_Olay_logo.png',
  ),
  NewsSourceItem(
    id: 'vansesi_gazetesi',
    title: 'Vansesi Gazetesi',
    subtitle: 'Van',
    badgeText: '65',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.vansesigazetesi.com/rss/sondakika',
    logoPath: 'assets/logos/65_Vansesi_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'sehrivan',
    title: 'Şehrivan',
    subtitle: 'Van',
    badgeText: '65',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.sehrivangazetesi.com/rss/son-dakika',
    logoPath: 'assets/logos/65_Şehrivan_logo.png',
  ),
  NewsSourceItem(
    id: 'i̇leri_gazetesi',
    title: 'İleri Gazetesi',
    subtitle: 'Yozgat',
    badgeText: '66',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.ilerigazetesi.com.tr/rss/sondakika',
    logoPath: 'assets/logos/66_İleri_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'yozgat_camlik',
    title: 'Yozgat Çamlık',
    subtitle: 'Yozgat',
    badgeText: '66',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.yozgatcamlik.com/service/rss.php',
    logoPath: 'assets/logos/66_Yozgat_Çamlık_logo.png',
  ),
  NewsSourceItem(
    id: 'yozgat_olay',
    title: 'Yozgat Olay',
    subtitle: 'Yozgat',
    badgeText: '66',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.yozgatolay.com/feed/',
    logoPath: 'assets/logos/66_Yozgat_Olay_logo.png',
  ),
  NewsSourceItem(
    id: 'pusula_gazetesi',
    title: 'Pusula Gazetesi',
    subtitle: 'Zonguldak',
    badgeText: '67',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.pusulagazetesi.com.tr/rss/sondakika',
    logoPath: 'assets/logos/67_Pusula_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'halkin_sesi',
    title: 'Halkın Sesi',
    subtitle: 'Zonguldak',
    badgeText: '67',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.halkinsesi.com.tr/rss/sondakika',
    logoPath: 'assets/logos/67_Halkın_Sesi_logo.png',
  ),
  NewsSourceItem(
    id: 'ozgur_halkin_sesi',
    title: 'Özgür Halkın Sesi',
    subtitle: 'Zonguldak',
    badgeText: '67',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.ozgurhalkinsesi.com.tr/rss.xml',
    logoPath: 'assets/logos/67_Özgür_Halkın_Sesi_logo.png',
  ),
  NewsSourceItem(
    id: 'yeni_aksaray',
    title: 'Yeni Aksaray',
    subtitle: 'Aksaray',
    badgeText: '68',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://yeniaksaray.com.tr/rss/son-dakika',
    logoPath: null,
  ),
  NewsSourceItem(
    id: 'aksaray_egemen',
    title: 'Aksaray Egemen',
    subtitle: 'Aksaray',
    badgeText: '68',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.aksarayegemen.com.tr/rss/news',
    logoPath: 'assets/logos/68_Aksaray_Egemen_logo.png',
  ),
  NewsSourceItem(
    id: 'aksaray68_haber',
    title: 'Aksaray68 Haber',
    subtitle: 'Aksaray',
    badgeText: '68',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.aksaray68haber.com.tr/rss.xml',
    logoPath: 'assets/logos/68_Aksaray68_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'bayburt_postasi',
    title: 'Bayburt Postası',
    subtitle: 'Bayburt',
    badgeText: '69',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.bayburtpostasi.com.tr/rss/sondakika',
    logoPath: 'assets/logos/69_Bayburt_Postası_logo.png',
  ),
  NewsSourceItem(
    id: 'bayburt_haber',
    title: 'Bayburt Haber',
    subtitle: 'Bayburt',
    badgeText: '69',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.bayburthaber.com/rss',
    logoPath: 'assets/logos/69_Bayburt_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'karaman_gundem',
    title: 'Karaman Gündem',
    subtitle: 'Karaman',
    badgeText: '70',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.karamangundem.com/rss',
    logoPath: 'assets/logos/70_Karaman_Gündem_logo.png',
  ),
  NewsSourceItem(
    id: 'karaman’da_uyanis',
    title: 'Karaman’da Uyanış',
    subtitle: 'Karaman',
    badgeText: '70',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.karamandauyanis.com/rss',
    logoPath: 'assets/logos/70_Karaman’da_Uyanış_logo.png',
  ),
  NewsSourceItem(
    id: 'i̇l_gazetesi',
    title: 'İl Gazetesi',
    subtitle: 'Kırıkkale',
    badgeText: '71',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.ilgazetesi.com.tr/service/rss.php',
    logoPath: 'assets/logos/71_İl_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'manset_gazetesi',
    title: 'Manşet Gazetesi',
    subtitle: 'Kırıkkale',
    badgeText: '71',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.mansetgazetesi.net/rss/son-dakika',
    logoPath: 'assets/logos/71_Manşet_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'gazete_kale',
    title: 'Gazete Kale',
    subtitle: 'Kırıkkale',
    badgeText: '71',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.gazetekale.com/service/rss.php',
    logoPath: 'assets/logos/71_Gazete_Kale_logo.png',
  ),
  NewsSourceItem(
    id: 'batman_cagdas',
    title: 'Batman Çağdaş',
    subtitle: 'Batman',
    badgeText: '72',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.batmancagdas.com/rss/sondakika',
    logoPath: 'assets/logos/72_Batman_Çağdaş_logo.png',
  ),
  NewsSourceItem(
    id: 'batman_pusula',
    title: 'Batman Pusula',
    subtitle: 'Batman',
    badgeText: '72',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.batmanpusula.com/rss/son-dakika',
    logoPath: 'assets/logos/72_Batman_Pusula_logo.png',
  ),
  NewsSourceItem(
    id: 'sirnak_haber_73',
    title: 'Şırnak Haber 73',
    subtitle: 'Şırnak',
    badgeText: '73',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://sirnakhaber73.com/service/rss.php',
    logoPath: 'assets/logos/73_Şırnak_Haber_73_logo.png',
  ),
  NewsSourceItem(
    id: 'sirnak_haber',
    title: 'Şırnak Haber',
    subtitle: 'Şırnak',
    badgeText: '73',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://sirnakhaber.com/service/rss.php',
    logoPath: 'assets/logos/73_Şırnak_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'sirnak_ajans',
    title: 'Şırnak Ajans',
    subtitle: 'Şırnak',
    badgeText: '73',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.sirnakajans.com/rss/son-dakika',
    logoPath: 'assets/logos/73_Şırnak_Ajans_logo.png',
  ),
  NewsSourceItem(
    id: 'bartin_halk',
    title: 'Bartın Halk',
    subtitle: 'Bartın',
    badgeText: '74',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.bartinhalkgazetesi.com.tr/rss',
    logoPath: 'assets/logos/74_Bartın_Halk_logo.png',
  ),
  NewsSourceItem(
    id: 'bartin_i̇nfo',
    title: 'Bartın İnfo',
    subtitle: 'Bartın',
    badgeText: '74',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.bartin.info/rss/son-dakika',
    logoPath: 'assets/logos/74_Bartın_İnfo_logo.png',
  ),
  NewsSourceItem(
    id: 'serhat_birikim',
    title: 'Serhat Birikim',
    subtitle: 'Ardahan',
    badgeText: '75',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://serhatbirikim.com.tr/rss.xml',
    logoPath: 'assets/logos/75_Serhat_Birikim_logo.png',
  ),
  NewsSourceItem(
    id: 'yesil_igdir',
    title: 'Yeşil Iğdır',
    subtitle: 'Iğdır',
    badgeText: '76',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.yesiligdir.com/rss/son-dakika',
    logoPath: 'assets/logos/76_Yeşil_Iğdır_logo.png',
  ),
  NewsSourceItem(
    id: 'igdir_dogus',
    title: 'Iğdır Doğuş',
    subtitle: 'Iğdır',
    badgeText: '76',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'http://www.igdirdogusgazetesi.com/rss.php',
    logoPath: 'assets/logos/76_Iğdır_Doğuş_logo.png',
  ),
  NewsSourceItem(
    id: 'guven_gazetesi',
    title: 'Güven Gazetesi',
    subtitle: 'Iğdır',
    badgeText: '76',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.guvengazetesi.com.tr/rss.xml',
    logoPath: 'assets/logos/76_Güven_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'yalova_gazetesi',
    title: 'Yalova Gazetesi',
    subtitle: 'Yalova',
    badgeText: '77',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.yalovagazetesi.com/rss/sondakika',
    logoPath: 'assets/logos/77_Yalova_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'yalova_hayat',
    title: 'Yalova Hayat',
    subtitle: 'Yalova',
    badgeText: '77',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.yalovahayat.com/rss',
    logoPath: 'assets/logos/77_Yalova_Hayat_logo.png',
  ),
  NewsSourceItem(
    id: 'haberci',
    title: 'Haberci',
    subtitle: 'Yalova',
    badgeText: '77',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://haberci.com.tr/feed',
    logoPath: 'assets/logos/77_Haberci_logo.png',
  ),
  NewsSourceItem(
    id: 'bolgenin_sesi',
    title: 'Bölgenin Sesi',
    subtitle: 'Karabük',
    badgeText: '78',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://bolgeninsesigazetesi.com/feed',
    logoPath: 'assets/logos/78_Bölgenin_Sesi_logo.png',
  ),
  NewsSourceItem(
    id: 'karabuk_derin_haber',
    title: 'Karabük Derin Haber',
    subtitle: 'Karabük',
    badgeText: '78',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.karabukderinhaber.com/rss/son-dakika',
    logoPath: 'assets/logos/78_Karabük_Derin_Haber_logo.png',
  ),
  NewsSourceItem(
    id: 'kilis_postasi',
    title: 'Kilis Postası',
    subtitle: 'Kilis',
    badgeText: '79',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.kilispostasi.com/rss.xml',
    logoPath: 'assets/logos/79_Kilis_Postası_logo.png',
  ),
  NewsSourceItem(
    id: 'kilis_olay',
    title: 'Kilis Olay',
    subtitle: 'Kilis',
    badgeText: '79',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.kilisolay.com/rss',
    logoPath: 'assets/logos/79_Kilis_Olay_logo.png',
  ),
  NewsSourceItem(
    id: 'basak_gazetesi',
    title: 'Başak Gazetesi',
    subtitle: 'Osmaniye',
    badgeText: '80',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.basakgazetesi.com/rss.xml',
    logoPath: 'assets/logos/80_Başak_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'hasret_gazetesi',
    title: 'Hasret Gazetesi',
    subtitle: 'Osmaniye',
    badgeText: '80',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.hasretgazetesi.com.tr/rss/son-dakika',
    logoPath: 'assets/logos/80_Hasret_Gazetesi_logo.png',
  ),
  NewsSourceItem(
    id: 'akdeniz_gazetesi',
    title: 'Akdeniz Gazetesi',
    subtitle: 'Osmaniye',
    badgeText: '80',
    badgeColor: Color(0xFF34495E),
    type: NewsSourceType.rss,
    url: 'https://www.akdenizgazetesi.com/rss/sondakika',
    logoPath: 'assets/logos/80_Akdeniz_Gazetesi_logo.png',
  ),
];

NewsSourceItem? findNewsSourceById(String id) {
  try {
    return kAllNewsSources.firstWhere(
      (source) => source.id.toLowerCase() == id.toLowerCase(),
    );
  } catch (_) {
    return null;
  }
}
