import 'package:flutter/material.dart';

class SourceChannel {
  final String id;
  final String name;
  final String category;
  final String badgeText;
  final Color badgeColor;
  final String channelHandle;
  final String youtubeVideoId;
  final String liveStreamUrl;
  final String embedUrl;
  final String thumbnailUrl;
  final bool isLive;
  final String programTitle;

  const SourceChannel({
    required this.id,
    required this.name,
    required this.category,
    required this.badgeText,
    required this.badgeColor,
    required this.channelHandle,
    required this.youtubeVideoId,
    required this.liveStreamUrl,
    required this.embedUrl,
    required this.thumbnailUrl,
    this.isLive = true,
    this.programTitle = 'Canlı Yayın & Güncel Bülten',
  });

  SourceChannel copyWith({
    String? id,
    String? name,
    String? category,
    String? badgeText,
    Color? badgeColor,
    String? channelHandle,
    String? youtubeVideoId,
    String? liveStreamUrl,
    String? embedUrl,
    String? thumbnailUrl,
    bool? isLive,
    String? programTitle,
  }) {
    return SourceChannel(
      id: id ?? this.id,
      name: name ?? this.name,
      category: category ?? this.category,
      badgeText: badgeText ?? this.badgeText,
      badgeColor: badgeColor ?? this.badgeColor,
      channelHandle: channelHandle ?? this.channelHandle,
      youtubeVideoId: youtubeVideoId ?? this.youtubeVideoId,
      liveStreamUrl: liveStreamUrl ?? this.liveStreamUrl,
      embedUrl: embedUrl ?? this.embedUrl,
      thumbnailUrl: thumbnailUrl ?? this.thumbnailUrl,
      isLive: isLive ?? this.isLive,
      programTitle: programTitle ?? this.programTitle,
    );
  }
}

const List<SourceChannel> initialLiveChannels = [
  SourceChannel(
    id: 'trt',
    name: 'TRT Haber',
    category: 'Ulusal Haber',
    badgeText: 'TRT',
    badgeColor: Color(0xFF0F52BA),
    channelHandle: '@trthaber',
    youtubeVideoId: 'myv0L5yK_rY',
    liveStreamUrl: 'https://www.youtube.com/@trthaber/live',
    embedUrl: 'https://www.youtube-nocookie.com/embed/myv0L5yK_rY?autoplay=1&playsinline=1&rel=0&modestbranding=1&enablejsapi=1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=800&q=80',
    programTitle: 'TRT Haber Canlı Yayın',
  ),
  SourceChannel(
    id: 'ntv',
    name: 'NTV Canlı',
    category: 'Ekonomi & Gündem',
    badgeText: 'NTV',
    badgeColor: Color(0xFF008751),
    channelHandle: '@NTV',
    youtubeVideoId: 'pqq5c6k70kk',
    liveStreamUrl: 'https://www.youtube.com/@NTV/live',
    embedUrl: 'https://www.youtube-nocookie.com/embed/pqq5c6k70kk?autoplay=1&playsinline=1&rel=0&modestbranding=1&enablejsapi=1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80',
    programTitle: 'NTV Canlı Yayın & Gündem',
  ),
  SourceChannel(
    id: 'haberturk',
    name: 'Habertürk TV',
    category: 'Gündem & Tartışma',
    badgeText: 'HT',
    badgeColor: Color(0xFFE50014),
    channelHandle: '@HaberturkTV',
    youtubeVideoId: 'CJHVSYHpVvc',
    liveStreamUrl: 'https://www.youtube.com/@HaberturkTV/live',
    embedUrl: 'https://www.youtube-nocookie.com/embed/CJHVSYHpVvc?autoplay=1&playsinline=1&rel=0&modestbranding=1&enablejsapi=1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80',
    programTitle: 'Habertürk TV Canlı',
  ),
  SourceChannel(
    id: 'sozcu',
    name: 'Sözcü TV',
    category: 'Haber & Gündem',
    badgeText: 'SZC',
    badgeColor: Color(0xFFD6181F),
    channelHandle: '@sozcutelevizyonu',
    youtubeVideoId: 'ztmY_cCtUl0',
    liveStreamUrl: 'https://www.youtube.com/@sozcutelevizyonu/live',
    embedUrl: 'https://www.youtube-nocookie.com/embed/ztmY_cCtUl0?autoplay=1&playsinline=1&rel=0&modestbranding=1&enablejsapi=1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800&q=80',
    programTitle: 'Sözcü TV Canlı Yayın',
  ),
  SourceChannel(
    id: 'cnnturk',
    name: 'CNN Türk',
    category: 'Haber & Dünya',
    badgeText: 'CNN',
    badgeColor: Color(0xFFCC0000),
    channelHandle: '@cnnturk',
    youtubeVideoId: '6N8_r2uwLEc',
    liveStreamUrl: 'https://www.youtube.com/@cnnturk/live',
    embedUrl: 'https://www.youtube-nocookie.com/embed/6N8_r2uwLEc?autoplay=1&playsinline=1&rel=0&modestbranding=1&enablejsapi=1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?w=800&q=80',
    programTitle: 'CNN Türk Canlı',
  ),
  SourceChannel(
    id: 'ahaber',
    name: 'A Haber',
    category: 'Haber & Politika',
    badgeText: 'AH',
    badgeColor: Color(0xFF0A2B66),
    channelHandle: '@ahaber',
    youtubeVideoId: 'b8B-c7Hmkic',
    liveStreamUrl: 'https://www.youtube.com/@ahaber/live',
    embedUrl: 'https://www.youtube-nocookie.com/embed/b8B-c7Hmkic?autoplay=1&playsinline=1&rel=0&modestbranding=1&enablejsapi=1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
    programTitle: 'A Haber Canlı Yayın',
  ),
  SourceChannel(
    id: 'haberglobal',
    name: 'Haber Global',
    category: 'Haber & Analiz',
    badgeText: 'HG',
    badgeColor: Color(0xFF2C3E50),
    channelHandle: '@HaberGlobal',
    youtubeVideoId: 'EqoCJ8BPxtE',
    liveStreamUrl: 'https://www.youtube.com/@HaberGlobal/live',
    embedUrl: 'https://www.youtube-nocookie.com/embed/EqoCJ8BPxtE?autoplay=1&playsinline=1&rel=0&modestbranding=1&enablejsapi=1',
    thumbnailUrl:
        'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
    programTitle: 'Haber Global Canlı',
  ),
  SourceChannel(
    id: 'tgrthaber',
    name: 'TGRT Haber',
    category: 'Gündem & Ekonomi',
    badgeText: 'TG',
    badgeColor: Color(0xFF16A085),
    channelHandle: '@tgrthaber',
    youtubeVideoId: 'WX29nlgdqho',
    liveStreamUrl: 'https://www.youtube.com/@tgrthaber/live',
    embedUrl: 'https://www.youtube-nocookie.com/embed/WX29nlgdqho?autoplay=1&playsinline=1&rel=0&modestbranding=1&enablejsapi=1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80',
    programTitle: 'TGRT Haber Canlı',
  ),
  SourceChannel(
    id: '24tv',
    name: '24 TV',
    category: 'Ulusal & Politika',
    badgeText: '24',
    badgeColor: Color(0xFF8E44AD),
    channelHandle: '@yirmidorttv',
    youtubeVideoId: '6B-nPOdP720',
    liveStreamUrl: 'https://www.youtube.com/@yirmidorttv/live',
    embedUrl: 'https://www.youtube-nocookie.com/embed/6B-nPOdP720?autoplay=1&playsinline=1&rel=0&modestbranding=1&enablejsapi=1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=800&q=80',
    programTitle: '24 TV Canlı Yayın',
  ),
  SourceChannel(
    id: 'tv100',
    name: 'TV100',
    category: 'Gündem & Tartışma',
    badgeText: '100',
    badgeColor: Color(0xFFE67E22),
    channelHandle: '@tv100',
    youtubeVideoId: '4WSvLRk83-c',
    liveStreamUrl: 'https://www.youtube.com/@tv100/live',
    embedUrl: 'https://www.youtube-nocookie.com/embed/4WSvLRk83-c?autoplay=1&playsinline=1&rel=0&modestbranding=1&enablejsapi=1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?w=800&q=80',
    programTitle: 'TV100 Canlı Yayın',
  ),
  SourceChannel(
    id: 'halktv',
    name: 'Halk TV',
    category: 'Haber & Tartışma',
    badgeText: 'HLK',
    badgeColor: Color(0xFFC0392B),
    channelHandle: '@Halktvkanali',
    youtubeVideoId: 'jHMsvYrf-UA',
    liveStreamUrl: 'https://www.youtube.com/@Halktvkanali/live',
    embedUrl: 'https://www.youtube-nocookie.com/embed/jHMsvYrf-UA?autoplay=1&playsinline=1&rel=0&modestbranding=1&enablejsapi=1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800&q=80',
    programTitle: 'Halk TV Canlı Yayın',
  ),
  SourceChannel(
    id: 'tele1',
    name: 'Tele1',
    category: 'Haber & Gündem',
    badgeText: 'TL1',
    badgeColor: Color(0xFF2980B9),
    channelHandle: '@tele1comtr',
    youtubeVideoId: '7YGQuEDOEyc',
    liveStreamUrl: 'https://www.youtube.com/@tele1comtr/live',
    embedUrl: 'https://www.youtube-nocookie.com/embed/7YGQuEDOEyc?autoplay=1&playsinline=1&rel=0&modestbranding=1&enablejsapi=1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80',
    programTitle: 'Tele1 TV Canlı',
  ),
  SourceChannel(
    id: 'yenisafak',
    name: 'Yeni Şafak',
    category: 'Gündem & Haber',
    badgeText: 'YŞ',
    badgeColor: Color(0xFFC0392B),
    channelHandle: '@yenisafak',
    youtubeVideoId: 'pw-ydbrK4CE',
    liveStreamUrl: 'https://www.youtube.com/@yenisafak/live',
    embedUrl: 'https://www.youtube-nocookie.com/embed/pw-ydbrK4CE?autoplay=1&playsinline=1&rel=0&modestbranding=1&enablejsapi=1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
    programTitle: 'Yeni Şafak Canlı',
  ),
];
